### ISSUE TITLE
500 error when deleting rules

### ISSUE THREAD

**Issue by Rayvenhaus** [binarygod/AmSYS#48]
Added an Item Rule with no issues. Went to delete the same rule and I get a 500 error:

75.109.16.63 - - [19/Jan/2018:18:24:39 +0000] "GET /system/admin/settings/rules/delete/1 HTTP/1.1" 500 901 "https://market.thedoubled.org/system/admin/settings/rules" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) $

**Comment by Aarondorn2** [comment]
Another user noted same behavior - I'm going to try and look at this tonight.

**Comment by Aarondorn2** [comment]
This has been corrected and merged to Release branch.  Please  run update.sh or otherwise pull the Release branch to update your application.
