### ISSUE TITLE
** URGENT ** ESI URL changed

### ISSUE THREAD

**Issue by ysm1mh** [binarygod/AmSYS#53]
hello, can you update AmSYS as the ESI url has changed it seems and login to amsys no longer works

**Comment by Aarondorn2** [comment]
Sorry for the super late response, and thank you for the pull request.  It looks like there was a second reference that needed to be changed in `EveBundle\API\ESI.php`.  I've updated the second reference and it appears to be working correctly again.

There was another reference that I did not update in a file that's not currently used.
